# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

BL <- function(y, x, c, maxSteps, hatEta, hatb, hatInvTauSq2, invSigb0, hatLambdaSqStar2, hatSigmaSq, aStar, bStar, alpha, gamma, progress) {
    .Call(`_Bayenet_BL`, y, x, c, maxSteps, hatEta, hatb, hatInvTauSq2, invSigb0, hatLambdaSqStar2, hatSigmaSq, aStar, bStar, alpha, gamma, progress)
}

BLSS <- function(y, x, c, maxSteps, hatEta, hatb, hatInvTauSq2, sg2, hatPiEta, invSigb0, hatLambdaSqStar2, hatSigmaSq, aStar, bStar, alpha, gamma, mu0, nu0, progress) {
    .Call(`_Bayenet_BLSS`, y, x, c, maxSteps, hatEta, hatb, hatInvTauSq2, sg2, hatPiEta, invSigb0, hatLambdaSqStar2, hatSigmaSq, aStar, bStar, alpha, gamma, mu0, nu0, progress)
}

QBL <- function(y, x, c, maxSteps, hatb, hatEta, hatTau, hatV, hatSg2, invSigb0, hatEtaSq2, theta, r, a, b, progress) {
    .Call(`_Bayenet_QBL`, y, x, c, maxSteps, hatb, hatEta, hatTau, hatV, hatSg2, invSigb0, hatEtaSq2, theta, r, a, b, progress)
}

QBLSS <- function(y, x, c, maxSteps, hatAlpha, hatBeta, hatTau, hatV, hatSg, ss2, invSigAlpha0, hatPi, hatEtaSq, theta, r1, a, b, sh1, sh0, progress) {
    .Call(`_Bayenet_QBLSS`, y, x, c, maxSteps, hatAlpha, hatBeta, hatTau, hatV, hatSg, ss2, invSigAlpha0, hatPi, hatEtaSq, theta, r1, a, b, sh1, sh0, progress)
}

